documents = [
	{
        "name": "The Time Machine",
        "description": "A man travels through time and witnesses the evolution of humanity.",
        "author": "H.G. Wells",
        "year": 1895,
    },
    {
        "name": "Ender's Game",
        "description": "A young boy is trained to become a military leader in a war against an alien race.",
        "author": "Orson Scott Card",
        "year": 1985,
    },
    {
        "name": "Brave New World",
        "description": "A dystopian society where people are genetically engineered and conditioned to conform to a strict social hierarchy.",
        "author": "Aldous Huxley",
        "year": 1932,
    },
    {
        "name": "The Hitchhiker's Guide to the Galaxy",
        "description": "A comedic science fiction series following the misadventures of an unwitting human and his alien friend.",
        "author": "Douglas Adams",
        "year": 1979,
    },
    {
        "name": "Dune",
        "description": "A desert planet is the site of political intrigue and power struggles.",
        "author": "Frank Herbert",
        "year": 1965,
    },
    {
        "name": "Foundation",
        "description": "A mathematician develops a science to predict the future of humanity and works to save civilization from collapse.",
        "author": "Isaac Asimov",
        "year": 1951,
    },
    {
        "name": "Snow Crash",
        "description": "A futuristic world where the internet has evolved into a virtual reality metaverse.",
        "author": "Neal Stephenson",
        "year": 1992,
    },
    {
        "name": "Neuromancer",
        "description": "A hacker is hired to pull off a near-impossible hack and gets pulled into a web of intrigue.",
        "author": "William Gibson",
        "year": 1984,
    },
    {
        "name": "The War of the Worlds",
        "description": "A Martian invasion of Earth throws humanity into chaos.",
        "author": "H.G. Wells",
        "year": 1898,
    },
    {
        "name": "The Hunger Games",
        "description": "A dystopian society where teenagers are forced to fight to the death in a televised spectacle.",
        "author": "Suzanne Collins",
        "year": 2008,
    },
    {
        "name": "The Andromeda Strain",
        "description": "A deadly virus from outer space threatens to wipe out humanity.",
        "author": "Michael Crichton",
        "year": 1969,
    },
    {
        "name": "The Left Hand of Darkness",
        "description": "A human ambassador is sent to a planet where the inhabitants are genderless and can change gender at will.",
        "author": "Ursula K. Le Guin",
        "year": 1969,
    },
    {
        "name": "The Three-Body Problem",
        "description": "Humans encounter an alien civilization that lives in a dying system.",
        "author": "Liu Cixin",
        "year": 2008,
    },
	{
        "name": "Cosmic Visions",
        "description": "An epic space opera depicting a galaxy-spanning conflict between ancient civilizations.",
        "author": "Maxwell Reynolds",
        "year": 2014,
    },
    {
        "name": "The Sorcerer's Legacy",
        "description": "A high fantasy saga following a young sorcerer's quest to restore balance to a fractured realm.",
        "author": "Eleanor Blackwood",
        "year": 2009,
    },
    {
        "name": "Cybernetic Evolution",
        "description": "In a cyberpunk future, a rebel group fights against an oppressive AI-controlled society.",
        "author": "Xander Drake",
        "year": 2021,
    },
    {
        "name": "Underworld Chronicles",
        "description": "Urban fantasy intertwining the modern world with hidden realms inhabited by mythical creatures.",
        "author": "Amelia Hart",
        "year": 2017,
    },
    {
        "name": "The Last Kingdom",
        "description": "Historical fiction chronicling the Viking invasion of Anglo-Saxon England.",
        "author": "Frederick Olsen",
        "year": 1998,
    },
    {
        "name": "The Art of Deception",
        "description": "A psychological thriller where nothing is as it seems, filled with twists and mind games.",
        "author": "Ava Preston",
        "year": 2013,
    },
    {
        "name": "The Forbidden City",
        "description": "An adventure tale set in ancient China, unveiling secrets within the emperor's palace.",
        "author": "Samuel Liu",
        "year": 2006,
    },
    {
        "name": "The Enchanted Forest",
        "description": "A children's fantasy story of friendship and bravery set in a magical forest.",
        "author": "Sophie Johnson",
        "year": 2010,
    },
    {
        "name": "The Dark Prophecy",
        "description": "Supernatural thriller exploring prophecies and the battle between light and darkness.",
        "author": "Gabriel Knight",
        "year": 2016,
    },
    {
        "name": "The Quest for Atlantis",
        "description": "A speculative adventure chronicling a quest to uncover the fabled lost city of Atlantis.",
        "author": "Emma Reynolds",
        "year": 2008,
    },
    {
        "name": "The Twilight Conspiracy",
        "description": "A paranormal mystery series revealing a conspiracy entwined with supernatural elements.",
        "author": "Nathan Black",
        "year": 2012,
    },
    {
        "name": "The Artisan's Secret",
        "description": "Historical romance entwining forbidden love and the mysteries of an artisan's workshop.",
        "author": "Olivia Wells",
        "year": 2004,
    },
    {
        "name": "The Phantom Menace",
        "description": "A political thriller delving into conspiracies and power struggles in a fictional world.",
        "author": "Henry Parker",
        "year": 2018,
    },
    {
        "name": "The Enigma Code",
        "description": "A World War II spy thriller based on true events of code-breaking and espionage.",
        "author": "Liam Thompson",
        "year": 2003,
    },
    {
        "name": "The Kingdom of Dreams",
        "description": "Magical realism intertwining dreams and reality in a mysterious kingdom.",
        "author": "Isabella Clarke",
        "year": 2011,
    },
    {
        "name": "The Forgotten Empire",
        "description": "An epic fantasy saga set in an ancient empire facing a prophesied downfall.",
        "author": "Lucas Knight",
        "year": 2015,
    },
    {
        "name": "The Maze Runner",
        "description": "A dystopian thriller where a group of teenagers navigate a deadly maze.",
        "author": "James Dashner",
        "year": 2009,
    },
    {
        "name": "The Witching Hour",
        "description": "A supernatural horror tale involving witchcraft and a cursed town.",
        "author": "Evelyn Black",
        "year": 2019,
    },
    {
        "name": "The Dragon's Legacy",
        "description": "High fantasy epic involving dragons, prophecies, and the fate of kingdoms.",
        "author": "Nathaniel Drake",
        "year": 2007,
    },
    {
        "name": "The Time Traveler's Diary",
        "description": "A science fiction adventure exploring paradoxes and the consequences of time travel.",
        "author": "Rachel Turner",
        "year": 2012,
    },
    {
        "name": "The Cursed Kingdom",
        "description": "A gothic tale of curses and secrets in a haunted kingdom shrouded in darkness.",
        "author": "Matthew Harrison",
        "year": 2005,
    },
    {
        "name": "The Phoenix Prophecy",
        "description": "A prophecy foretells the rise of a hero in a world threatened by impending doom.",
        "author": "Charlotte White",
        "year": 2014,
    },
    {
        "name": "The Midnight Society",
        "description": "A mystery series revolving around a secret society investigating supernatural occurrences.",
        "author": "Christopher Adams",
        "year": 2013,
    },
    {
        "name": "The Bloodline Legacy",
        "description": "A vampire fantasy delving into ancient bloodlines and supernatural politics.",
        "author": "Sophia Reynolds",
        "year": 2017,
    },
    {
        "name": "The Elemental Chronicles",
        "description": "An elemental fantasy saga featuring heroes wielding the powers of nature.",
        "author": "Daniel Carter",
        "year": 2016,
    },
    {
        "name": "The Night Circus",
        "description": "A magical tale centered around a mysterious circus that appears only at night.",
        "author": "Erin Morgenstern",
        "year": 2011,
    },
    {
        "name": "The Secret Garden",
        "description": "A classic children's story of a hidden garden bringing hope and healing to its caretakers.",
        "author": "Frances Hodgson Burnett",
        "year": 1911,
    },
    {
        "name": "The Martian",
        "description": "A survival story of an astronaut stranded on Mars, fighting to stay alive and return home.",
        "author": "Andy Weir",
        "year": 2014,
    },
    {
        "name": "The Nightingale",
        "description": "Historical fiction set in World War II, following two sisters' experiences during the war.",
        "author": "Kristin Hannah",
        "year": 2015,
    },
    {
        "name": "The Silent Patient",
        "description": "A psychological thriller revolving around a woman's sudden and inexplicable silence after a tragic event.",
        "author": "Alex Michaelides",
        "year": 2019,
    },
    {
        "name": "Galactic Odyssey",
        "description": "Explorers venture into uncharted regions of space, encountering ancient civilizations and cosmic anomalies.",
        "author": "Victoria Roberts",
        "year": 2016,
    },
    {
        "name": "The Alchemy of Souls",
        "description": "A forbidden alchemical experiment leads to unexpected consequences, blurring the lines between science and magic.",
        "author": "Jonathan Turner",
        "year": 2007,
    },
    {
        "name": "Whispers of the Stars",
        "description": "An astronomer uncovers enigmatic messages from celestial bodies, hinting at an extraterrestrial intelligence.",
        "author": "Rachel Lewis",
        "year": 2019,
    },
    {
        "name": "The Quantum Paradox",
        "description": "Parallel universes collide, creating a crisis that only a group of scientists can avert.",
        "author": "Simon Foster",
        "year": 2010,
    },
    {
        "name": "Dreams of Tomorrow",
        "description": "In a post-apocalyptic world, a group of survivors strive to rebuild society while haunted by visions of a lost civilization.",
        "author": "Isabelle Martin",
        "year": 2025,
    },
    {
        "name": "Echoes from the Abyss",
        "description": "A deep-sea expedition encounters mysterious creatures and remnants of an ancient underwater civilization.",
        "author": "Matthew Coleman",
        "year": 2014,
    },
    {
        "name": "The Unseen Chronicles",
        "description": "An ancient tome holds the key to unlocking forbidden knowledge, attracting the attention of dark forces.",
        "author": "Sophia Bennett",
        "year": 2002,
    },
    {
        "name": "Empires of Dust",
        "description": "Amidst political intrigue and betrayal, an empire teeters on the brink of collapse as revolutionaries rise.",
        "author": "Daniel Thompson",
        "year": 1995,
    },
    {
        "name": "Whispers in the Wind",
        "description": "A nomadic tribe navigates a world where whispers carry prophecies and warnings of an impending catastrophe.",
        "author": "Grace Harrison",
        "year": 2009,
    },
    {
        "name": "Serpents of the Sands",
        "description": "Adventurers seek an ancient artifact rumored to grant ultimate power in a treacherous desert.",
        "author": "Maxwell Wright",
        "year": 2011,
    },
    {
        "name": "Chronicles of Illusion",
        "description": "Illusionists wield magic that blurs reality, and a young apprentice discovers the secrets behind their power.",
        "author": "Emma Turner",
        "year": 2004,
    },
    {
        "name": "Echoes of Destiny",
        "description": "Prophecies entwine the fates of unlikely heroes, shaping the outcome of a world on the brink of war.",
        "author": "Nathan Carter",
        "year": 2017,
    },
    {
        "name": "The Last Frontier",
        "description": "Pioneers embark on a perilous journey to the far reaches of space, seeking a new home for humanity.",
        "author": "Lillian Parker",
        "year": 2028,
    },
    {
        "name": "Legends of the Eternal Flame",
        "description": "A quest to reignite a mythical flame ensues, as darkness threatens to engulf the world in eternal night.",
        "author": "Elijah Hughes",
        "year": 2006,
    },
    {
        "name": "Echoes from the Future",
        "description": "Messages from a future civilization provide insights into the fate of humanity, altering the present course of events.",
        "author": "Madison Foster",
        "year": 2023,
    },
    {
        "name": "The Enigma of Ages",
        "description": "Ancient relics unlock a hidden truth that challenges the perception of history and the origins of humanity.",
        "author": "Jackson Clarke",
        "year": 2013,
    },
    {
        "name": "Whispers in the Shadows",
        "description": "In a realm between reality and dreams, mysterious whispers beckon adventurers to uncover hidden secrets.",
        "author": "Ava Johnson",
        "year": 2021,
    },
    {
        "name": "Empires Lost in Time",
        "description": "A chronicle of lost civilizations across different epochs, unraveling the mysteries of their disappearance.",
        "author": "Noah Edwards",
        "year": 2001,
    },
    {
        "name": "Echoes of the Unknown",
        "description": "An ancient artifact stirs echoes from distant realms, calling forth heroes to face an otherworldly threat.",
        "author": "Hailey Wilson",
        "year": 2018,
    },
    {
        "name": "Sands of Eternity",
        "description": "A mythical desert conceals secrets of an immortal society, guarded by powerful elemental forces.",
        "author": "Gabriel Martinez",
        "year": 2005,
    },
    {
        "name": "The Alchemist's Legacy",
        "description": "A legacy passed down through generations sparks a quest to uncover the hidden truths of alchemy.",
        "author": "Chloe Adams",
        "year": 2012,
    },
    {
        "name": "Whispers in Time's Embrace",
        "description": "Temporal anomalies intertwine with forbidden love, challenging the boundaries of reality and destiny.",
        "author": "Lucas Baker",
        "year": 2019,
    },
    {
        "name": "Echoes of the Celestial Realm",
        "description": "Visions from a celestial realm foretell a cosmic event that could reshape the fabric of the universe.",
        "author": "Sophie Thompson",
        "year": 2020,
    },
    {
        "name": "The Lost Chronicles",
        "description": "Lost writings discovered in an ancient library reveal forgotten tales of heroes and mythical creatures.",
        "author": "Oliver Harris",
        "year": 2014,
    },
    {
        "name": "Echoes of Forgotten Realms",
        "description": "A journey through forgotten realms unveils a world where myths and legends come to life.",
        "author": "Aria White",
        "year": 2016,
    },
    {
        "name": "Whispers of the Eternal Forest",
        "description": "Enigmatic whispers lead travelers on a quest through an eternal forest with magical properties.",
        "author": "Jacob Turner",
        "year": 2022,
    },
    {
        "name": "The Enigma of Shadows",
        "description": "A mysterious figure weaves enigmatic tales that blur the lines between reality and imagination.",
        "author": "Luna Carter",
        "year": 2015,
    },
    {
        "name": "Echoes from the Edge of Time",
        "description": "Echoes from the edge of time reveal ancient prophecies that foretell an impending cosmic cataclysm.",
        "author": "David Foster",
        "year": 2024,
    },
    {
        "name": "The Quantum Echo",
        "description": "A quantum experiment yields unexpected results, echoing across multiple realities and timelines.",
        "author": "Emily Thompson",
        "year": 2027,
    }
]